# Generated by Django 4.0.5 on 2022-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_nose', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('y_nose', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('x_shoulder', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('y_shoulder', models.DecimalField(decimal_places=2, default='', max_digits=4)),
            ],
        ),
    ]
