# Generated by Django 4.0.5 on 2022-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='record_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='x_nose',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='x_shoulder',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='y_nose',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='y_shoulder',
            field=models.IntegerField(default=''),
        ),
    ]
