# Generated by Django 4.0.5 on 2022-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamApp', '0002_person_record_id_alter_person_x_nose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='record_id',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
